import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center min-h-screen flex items-center justify-center">
        <h1 className="text-3xl font-bold underline">
          Working!
        </h1>
      </main>

      <footer className=" text-center bg-black text-white py-4">
        <p>Footer</p>
      </footer>
    </div>
  )
}
